CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock_qty INT NOT NULL DEFAULT 0,
    image_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT uq_cart UNIQUE (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(30) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    price_at_purchase DECIMAL(10,2) NOT NULL,
    quantity INT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Seed Default Accounts (Plain password: Password@123)
MERGE INTO users (id, name, email, password_hash, role) KEY(email) VALUES
(1, 'System Administrator', 'admin@vtmart.com', 'Password@123', 'ADMIN'),
(2, 'Official Seller', 'seller@vtmart.com', 'Password@123', 'SELLER'),
(3, 'Test Buyer', 'buyer@vtmart.com', 'Password@123', 'BUYER');

-- Seed Gym & Fitness Catalog Products
MERGE INTO products (id, seller_id, name, description, category, price, stock_qty, image_url) KEY(id) VALUES
(1, 2, 'Rubber Hex Dumbbell Set (20kg)', 'Durable cast iron hex dumbbells with ergonomic chrome handles and rubber coating.', 'Free Weights', 4499.00, 25, 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?w=800'),
(2, 2, 'Commercial Motorized Treadmill', '3.5 HP AC motor treadmill with auto-incline, shock absorption, and LED display console.', 'Machines', 54999.00, 5, 'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800'),
(3, 2, 'Olympic Barbell 20kg (7ft)', 'High-tensile steel barbell with 1500lb capacity and needle bearings for smooth spin.', 'Free Weights', 7999.00, 15, 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800'),
(4, 2, 'Heavy-Duty Power Rack Cage', 'Solid steel power cage with safety spotters, multi-grip pull-up bar, and J-hooks.', 'Machines', 24999.00, 8, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800'),
(5, 2, 'Adjustable Workout Bench (FID)', 'Multi-angle Flat, Incline, and Decline workout bench with high-density padding.', 'Benches', 6499.00, 20, 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800'),
(6, 2, 'Resistance Bands Set (5 Levels)', 'Premium latex exercise loop bands with handles, door anchor, and carry pouch.', 'Accessories', 999.00, 40, 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800');

